### ISSUE TITLE
Please change the Launch Library link to Launch Library 2

### ISSUE THREAD

**Issue by Nosudrum** [bogdandm/json2python-models#34]
As stated on the Launch Library website since early 2020, support for the API provided from the launchlibrary.net URL has come to an end and the API will be closing down on December 31, 2020. Starting November 1 there will be a launch asking to move to its successor : Launch Library 2.

Please update the links in your code and documentation to the new Launch Library 2 url.
You can find more details on The Space Devs website and Discord server:
https://thespacedevs.com/
https://discord.gg/p7ntkNA

Thanks a lot,

The Space Devs team

**Comment by bogdandm** [comment]
Thanks, I updated URL in example script.
