### ISSUE TITLE
add yaml , ini

### ISSUE THREAD

**Issue by arita37** [bogdandm/json2python-models#37]
Can you add

Yaml
Ini file,loader

it would make very generic

thanks vm

**Comment by bogdandm** [comment]
Do you mean "generate python models for data structure in yaml/ini file"? Yaml files won't be too difficult to implement. Ini files - I don't not know how useful it would be, I can hardly imagine this use case. 
Anyway I could take a look, but dont know when (and PR are always welcome).

**Comment by arita37** [comment]
Yes, exactly

Many config files are in .yaml

**Comment by bogdandm** [comment]
`--input-type` argument added - https://pypi.org/project/json2python-models/0.2.4/
