### ISSUE TITLE
i think it needs the \n quotation

### ISSUE THREAD

**Issue by MarsBatya** [bogdandm/json2python-models#42]
## Describe
i liked the idea of this package a lot, i tried to use it and i discovered that the generated code breaks if the Literal string has a newline charachter

## Reproduce
**Package version**: latest
run: json2models -m Lang en.json -f dataclasses > lang.py
JSON data:
```json
{
    "start": {
        "hello": "hi\nbye"
    }
}
```

## Actual result
Class code:
```python
@dataclass
class Lang:
    start: 'Start'

@dataclass
class Start:
    hello: Literal["hi
bye"]
```

## Expected result
Class code:
```python
@dataclass
class Lang:
    start: 'Start'

@dataclass
class Start:
    hello: Literal["hi\nbye"]
```

## Additional context
i found out that there is already a quotation of ' and \ in json_to_models/dynamic_typing/complex.py: StringLiteral.\_\_init\_\_, but i am too new to opensource to open a PR and not break anything else 😅

**Comment by bogdandm** [comment]
Thank you for reporting. Fixed in #43
```python
r"""
generated by json2python-models v0.2.4 at Thu Mar 10 12:27:07 2022
command: /opt/projects/json2python-models/venv/bin/json2models -m Lang en.json -f dataclasses
"""
from dataclasses import dataclass, field
from typing_extensions import Literal


@dataclass
class Lang:
    start: 'Start'


@dataclass
class Start:
    hello: Literal["hi\nbye"]
```

**Comment by bogdandm** [comment]
Hotfix 0.2.5 released https://pypi.org/project/json2python-models/0.2.5/

**Comment by MarsBatya** [comment]
> Hotfix 0.2.5 released https://pypi.org/project/json2python-models/0.2.5/

thankies bro 👍🏻
