### ISSUE TITLE
SQLModel support

### ISSUE THREAD

**Issue by izzues** [bogdandm/json2python-models#49]
Thanks for your work!

[SQLModel](https://sqlmodel.tiangolo.com/) models are built on top of and compatible with Pydantic and SQLAlchemy, which avoids code duplication. Are there any plans to support it as output? Or any automated way to convert from one of the currently supported outputs to it?

**Comment by bogdandm** [comment]
I'm not familiar with [SQLModel](https://sqlmodel.tiangolo.com/) and do not have plans for it, but looks like it will require only some templates changes at https://github.com/bogdandm/json2python-models/blob/master/json_to_models/models/pydantic.py#L23 (by inheritancing PydanticModelCodeGenerator).

**Comment by bogdandm** [comment]
Added in v0.3.0 (basic support, relationships and fk are not supported)
