### ISSUE TITLE
Generator would parse version number as float string

### ISSUE THREAD

**Issue by raymond-u** [bogdandm/json2python-models#50]
## Describe

I encountered a problem that the class generator seems to parse version number as float or float strings.

I'm using the latest version installed with pip, and I used the following command to generate the model.
```bash
$ json2models -s nested --max-strings-literals 0 -m VersionInfo version_info.json >version_info.py
```

## Reproduce
**Package version**: 0.2.7
JSON data:
```json
{
	"Version": [{
		"Name": "1.1",
		"Url": "https://foo"
	}, {
		"Name": "1.2",
		"Url": "https://foo"
	}]
}
```

## Actual result
Class code:
```python
from json_to_models.dynamic_typing import FloatString
from typing import List


class VersionInfo:
    class Version:
        name: FloatString
        url: str

    version: List['Version']
```

## Expected result
Class code:
```python
from typing import List


class VersionInfo:
    class Version:
        name: str
        url: str

    version: List['Version']
```

## Additional context

I'd like an option to disable all string converters, if possible (e.g., --disable-strings-converters).
Thanks for the great tool!

**Comment by bogdandm** [comment]
Thank you for the report. It is definitely not a bug, because this string could be parsed to float and there is no indication why it should not. However some CLI argument to disable this logic (completly or only for some field) would be nice. I will look into it when I have free time.

**Comment by bogdandm** [comment]
Seems good now:
```python
venv ❯ python -m json_to_models -s nested --max-strings-literals 0 -m VersionInfo 1.json --disable-str-serializable-types float                        
r"""
generated by json2python-models v0.2.7 at Fri Nov 11 19:10:08 2022
command: /opt/projects/json2python-models/json_to_models/__main__.py -s nested --max-strings-literals 0 -m VersionInfo 1.json --disable-str-serializable-types float
"""
from typing import List


class VersionInfo:
    class Version:
        name: str
        url: str

    version: List['Version']
```
I will make a minor release probably next week, want to fix one more issue. For you can install it from master.
