### ISSUE TITLE
Not able to install with pip >24.1 version

### ISSUE THREAD

**Issue by sumeet30** [bogdandm/json2python-models#57]
## Describe
This cannot be installed with pip version >=24.1. 

## Actual result
WARNING: Ignoring version 0.3.0 of json2python-models since it has invalid metadata:
Requested json2python-models==0.3.0 from https://files.pythonhosted.org/packages/89/23/467ea3c1157d320dfe8652a32e0005ba8cd25f9987a31de18dae9f8ace27/json2python_models-0.3.0-py3-none-any.whl (from -r framework_requirements.txt (line 22)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    python-dateutil (>=2.7.*)
                     ~~~~~~^
Please use pip<24.1 if you need to use this version.

**Comment by fsecada01** [comment]
I have a PR to address this, if you want to take a look.  https://github.com/bogdandm/json2python-models/pull/58

**Comment by bogdandm** [comment]
Sorry for late response, was very busy last months
@fsecada01 thank you, I will take a look

**Comment by bogdandm** [comment]
Version 0.3.1 has been released
```
venv ❯ pip install -U pip
Successfully installed pip-24.2

venv ❯ pip install json2python-models==0.3.1
...

venv ❯ json2models --help                   
usage: json2models [-h] [-m <Model name> [<JSON lookup>] <File path or pattern> [...]] [-i {json,yaml,ini}] [-o FILE]
                   [-f {base,attrs,dataclasses,pydantic,sqlmodel,custom}] [-s {nested,flat}] [--datetime] [--strings-converters]
                   [--max-strings-literals NUMBER] [--disable-unicode-conversion] [--merge MERGE [MERGE ...]] [--dict-keys-regex RegEx [RegEx ...]]
                   [--dict-keys-fields FIELD NAME [FIELD NAME ...]] [--code-generator CODE_GENERATOR] [--code-generator-kwargs [NAME=VALUE ...]]
                   [--preamble PREAMBLE] [--disable-str-serializable-types [TYPE ...]] [-l <Model name> <JSON lookup> <JSON file>]

````
